---
title: "United States Minimum Wage State Comparison, 1968-2017"
author: "FlightGuys"
date: "5/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
<<<<<<< HEAD
With the rising costs of living across the United States, this [report](https://www.theguardian.com/commentisfree/2018/jul/29/us-economy-workers-paycheck-robert-reich) 
show that citizens are living paycheck to paycheck as a means of survivability. As of 2019, employment 
rates are statistically low in comparison to prior years but does not answer the question of why 
the majority still struggle with obtaining monetary safety nets. Our goal is to 
identify associations of consumer spending based on minimum wage values per state 
in order to address economic affordability based on mininum wage and life sustainability.
=======
With the rising costs of living across the United States, [reports](https://www.theguardian.com/commentisfree/2018/jul/29/us-economy-workers-paycheck-robert-reich)
show that citizens are living paycheck to paychek as a means of survivability. 
>>>>>>> Kevin_Branch




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
